name: Publish Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - uses: actions/checkout@v3     #Clone le repository
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"


      - name: Install dependencies 
        run: |
          pip install backports.tarfile==1.2.0 importlib-metadata==8.0.0 jaraco.collections==5.1.0 platformdirs==4.2.2 tomli==2.0.1 sphinx-autobuild==2025.8.25
    

      - name: Sphinx build
        run: |
          sphinx-build source build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true