name: Test Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - uses: actions/checkout@v3     #Clone le repository
        with:
          fetch-depth: 0  # Important pour sphinx-multiversion
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"


      - name: Install dependencies 
        run: |
          pip install exceptiongroup==1.3.0 furo==2025.9.25 importlib-metadata==8.7.0 ipykernel==7.1.0 jaraco.collections==5.1.0 make==0.1.6.post2 pandoc==2.4 pickleshare==0.7.5 sphinx-autobuild==2025.8.25 sphinx-book-theme==1.1.4 sphinx-multiversion==0.2.4 sphinx-rtd-theme==3.0.2 sphinxcontrib-exceltable==0.3.0 sphinxcontrib-matlabdomain==0.22.1 tomli==2.0.1 uv==0.9.17    

      - name: Clean build directory
        run: |
          rm -rf sphynx_documentation/build
      
      - name: Sphinx build
        run: |
          rm -rf sphynx_documentation/build
          sphinx-multiversion -W --keep-going sphynx_documentation/source sphynx_documentation/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: sphynx_documentation/build
          force_orphan: true